### ISSUE TITLE
No longer work in blender ver 4.0+ 

### ISSUE THREAD

**Issue by Yuki-Soul** [BlenderBoi/Vertex_Group_Utils#3]
Error message popup when I try to enable this add-on in blender ver 4.0+

**Comment by WillyB1337** [comment]
@BlenderBoi 


```
Traceback (most recent call last):
  File "C:\Users\super\3D Objects\Blender\Installs\custom\blender-4.0.1-windows-x64\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Vertex-Group-Utils-master\__init__.py", line 25, in register
    VGU_Operators.register()
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Vertex-Group-Utils-master\VGU_Operators.py", line 1737, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'VGU_OT_Duplicate_Selected_Objects_Mesh_And_Rename_Vertex_Groups'
```

**Comment by BlenderBoi** [comment]
For now, Please use the Hotfix 4.0 Branch for Blender 4.0
https://github.com/BlenderBoi/Vertex_Group_Utils/tree/hotfix4.0

**Comment by WillyB1337** [comment]
> For now, Please use the Hotfix 4.0 Branch for Blender 4.0 https://github.com/BlenderBoi/Vertex_Group_Utils/tree/hotfix4.0

```
Traceback (most recent call last):
  File "C:\Users\super\3D Objects\Blender\Installs\custom\blender-4.0.1-windows-x64\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Users\super\3D Objects\Blender\Installs\custom\blender-4.0.1-windows-x64\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Vertex_Group_Utils-hotfix4'
```

**Comment by BlenderBoi** [comment]
Try rename the folder in the zip to remove -hotfix4 from the name

**Comment by WillyB1337** [comment]
That did the trick.

It is odd but workable.
Thanks!
